//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_CharityWebsite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CharityManagementEntities : DbContext
    {
        public CharityManagementEntities()
            : base("name=CharityManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHIENDICH> CHIENDICHes { get; set; }
        public virtual DbSet<QUANLY> QUANLies { get; set; }
        public virtual DbSet<CHITIETQUYENGOP> CHITIETQUYENGOPs { get; set; }
        public virtual DbSet<QUYENGOP> QUYENGOPs { get; set; }
        public virtual DbSet<NGUOIDUNG> NGUOIDUNGs { get; set; }
        public virtual DbSet<THUVIEN> THUVIENs { get; set; }
        public virtual DbSet<ADMIN> ADMINs { get; set; }
        public virtual DbSet<LIENHE> LIENHEs { get; set; }
    
        public virtual ObjectResult<sp_QuyenGopTheoThang_Result> sp_QuyenGopTheoThang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_QuyenGopTheoThang_Result>("sp_QuyenGopTheoThang");
        }
    }
}
