//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_CharityWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHIENDICH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHIENDICH()
        {
            this.CHITIETQUYENGOPs = new HashSet<CHITIETQUYENGOP>();
        }
    
        public int MaCD { get; set; }
        public string TenCD { get; set; }
        public string MoTa { get; set; }
        public int MaQL { get; set; }
        public string AnhBia { get; set; }
        public Nullable<decimal> TongQuy { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual QUANLY QUANLY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETQUYENGOP> CHITIETQUYENGOPs { get; set; }
    }
}
