//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_CharityWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETQUYENGOP
    {
        public int MaQG { get; set; }
        public int MaCD { get; set; }
        public Nullable<decimal> SoTienQG { get; set; }
    
        public virtual CHIENDICH CHIENDICH { get; set; }
        public virtual QUYENGOP QUYENGOP { get; set; }
    }
}
