//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_CharityWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUANLY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUANLY()
        {
            this.CHIENDICHes = new HashSet<CHIENDICH>();
        }
    
        public int MaQL { get; set; }
        public string TenQL { get; set; }
        public string EmailQL { get; set; }
        public string SDTQL { get; set; }
        public string TieuSu { get; set; }
        public string AnhQL { get; set; }
        public string ChucVu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHIENDICH> CHIENDICHes { get; set; }
    }
}
