//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_CharityWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUYENGOP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUYENGOP()
        {
            this.CHITIETQUYENGOPs = new HashSet<CHITIETQUYENGOP>();
        }
    
        public int MaQG { get; set; }
        public Nullable<int> MaND { get; set; }
        public Nullable<decimal> SoTien { get; set; }
        public Nullable<System.DateTime> NgayQuyenGop { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETQUYENGOP> CHITIETQUYENGOPs { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
    }
}
